In [2]:
# @title Data manipulation with Python
import pandas as pd

url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

In [3]:
# @title menampilkan dataset
print(df.head())
df.info()
display (df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
# @title melihat missing value
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
# @title Menghapus Kolom yang tidak relevan untuk pelatihan model
kolom_sampah = ['PassengerId', 'Name', 'Ticket', 'Cabin', 'Embarked']
df_bersih = df.drop(columns=kolom_sampah)

In [6]:
df_bersih

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0           0       3    male  22.0      1      0   7.2500
1           1       1  female  38.0      1      0  71.2833
2           1       3  female  26.0      0      0   7.9250
3           1       1  female  35.0      1      0  53.1000
4           0       3    male  35.0      0      0   8.0500
..        ...     ...     ...   ...    ...    ...      ...
886         0       2    male  27.0      0      0  13.0000
887         1       1  female  19.0      0      0  30.0000
888         0       3  female   NaN      1      2  23.4500
889         1       1    male  26.0      0      0  30.0000
890         0       3    male  32.0      0      0   7.7500

[891 rows x 7 columns]

In [7]:
# @title Menangani missing value pada kolom age
median_umur = df_bersih['Age'].median()
df_bersih['Age'] = df_bersih['Age'].fillna(median_umur)

In [8]:
# @title Menghapus sisa baris yang masih memiliki missing values (misal ada 2 baris kosong di
# kolom 'Embarked')
df_bersih = df_bersih.dropna()

In [13]:
# @title Melihat kembali sum of missing value
# tulis lagi yak gimana lihatnya 🤭
df_bersih.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
dtype: int64

In [14]:
# @title One hot encoding kalo kategoorikal
df_final = pd.get_dummies(df_bersih, columns=['Sex'], drop_first=True)
df_final = df_final.rename(columns={'Sex_male': 'Sex'})
df_final['Sex'] = df_final['Sex'].astype(int)

In [15]:
# @title normalisasi menggunakan min max scaler
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
df_std = std_scaler.fit_transform(df_final)

In [16]:
# @title tampilkan kembali hasil data final
df_final

     Survived  Pclass   Age  SibSp  Parch     Fare  Sex
0           0       3  22.0      1      0   7.2500    1
1           1       1  38.0      1      0  71.2833    0
2           1       3  26.0      0      0   7.9250    0
3           1       1  35.0      1      0  53.1000    0
4           0       3  35.0      0      0   8.0500    1
..        ...     ...   ...    ...    ...      ...  ...
886         0       2  27.0      0      0  13.0000    1
887         1       1  19.0      0      0  30.0000    0
888         0       3  28.0      1      2  23.4500    0
889         1       1  26.0      0      0  30.0000    1
890         0       3  32.0      0      0   7.7500    1

[891 rows x 7 columns]